[project]
name = "vibely-news-scraper"
version = "0.1.0"
description = "Vibe-coded news and image scraper. LET'S GOOO!!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.0",
    "pyinstaller>=6.14.2",
]
